/* Generated By:JavaCC: Do not edit this line. SprolConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SprolConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROGRAM = 6;
  /** RegularExpression Id. */
  int PROC = 7;
  /** RegularExpression Id. */
  int VAR = 8;
  /** RegularExpression Id. */
  int BEGIN = 9;
  /** RegularExpression Id. */
  int END = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int ID = 12;
  /** RegularExpression Id. */
  int CONST = 13;
  /** RegularExpression Id. */
  int STRING = 14;
  /** RegularExpression Id. */
  int INTEGER = 15;
  /** RegularExpression Id. */
  int DECIMAL = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"program\"",
    "\"proc\"",
    "\"var\"",
    "\"begin\"",
    "\"end\"",
    "\"if\"",
    "<ID>",
    "\"<const>\"",
    "<STRING>",
    "<INTEGER>",
    "<DECIMAL>",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\":=\"",
    "\".\"",
    "\"~\"",
    "\"<>\"",
    "\",\"",
  };

}
